### ISSUE TITLE
feature request: reset board

### ISSUE THREAD

**Issue by kmcnaught** [Hizoul/optikey-boardlayout#1]
I've been using your wepage to make Optikey board layouts, thanks, it's really helpful. 

Since I generally make boards from scratch, rather than adapting existing ones, I often find myself wanting a completely blank MxN size board to start with. Particularly since I often leave gaps between keys, e.g. like the game pad example. I haven't found any way to quickly reset keys in the existing webpage, but it would be a really useful feature. (but do let me know if I missed something!)

**Comment by Hizoul** [comment]
I'm glad to hear the software is of use to people :) And no you did not miss anything feature wise this tool is absolutely barebones (but it did grow in options since OptiKey V3).

I added the ability to create new empty boards of any size to the File Card to address your use case.
Let me know if it works the way you imagined it would!

**Comment by kmcnaught** [comment]
This is exactly what I imagined, thanks! One bug though - when I add a DynamicKey to the now-empty layout, the XML key type is `undefined`, i.e. I get this:

```
<undefined Row="3" Col="7">
        <Text></Text>
        <Label>hello</Label>
        <Symbol>ArrowPointingToBottomRightBoundaryIcon</Symbol>
</undefined>
```
instead of 
```
<DynamicKey Row="3" Col="7">
        <Text></Text>
        <Label>hello</Label>
        <Symbol>ArrowPointingToBottomRightBoundaryIcon</Symbol>
</DynamicKey>
```

**Comment by Hizoul** [comment]
Should be fixed now!
