### ISSUE TITLE
Bug in drag & drop to swap

### ISSUE THREAD

**Issue by kmcnaught** [Hizoul/optikey-boardlayout#6]
I only just discovered the drag & drop behaviour - this is really useful!

However, I've found sometimes the page breaks (goes empty) when I swap keys near the bottom of the keyboard, which means I have to refresh and lose my changes. 

I'm not sure exactly the circumstances that trigger it, but it seems pretty reliable if I'm swapping into/out of the bottom row, and one of the keys (source or destination) is blank. 

Here's a demo:
https://www.loom.com/share/d587b62e91d74dba873e747cbec932c7

**Comment by Hizoul** [comment]
> Here's a demo
Thank you so much for this! I was  instantly able to identify the problem thanks to it and pushed a fix.
The problem was that you were switching to an invalid / empty Index. The layout code can't display two keys wide entries, so there is an empty key next to the spacebar. The code didn't handle it correctly if a key was switched to an empty key resulting in an NPE but it should be resolved now :)

Thanks for helping improve the software through your report!
